// /sitemap.xml (see vercel.json). The sitemap itself is generated by the backend from
// the product database; this edge function relays it and lets Vercel's CDN keep a copy,
// so crawlers still get a sitemap instantly while the Render backend is asleep.
export const config = { runtime: "edge" };

const API_ORIGIN = (
  process.env.SEO_API_URL ||
  process.env.VITE_API_URL ||
  "https://knotts-jewlery-1.onrender.com/api"
)
  .replace(/\/$/, "")
  .replace(/\/api$/, "");

// Long enough for a sleeping Render instance to start in most cases.
const TIMEOUT_MS = 20000;

export default async function handler() {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(`${API_ORIGIN}/sitemap.xml`, { signal: controller.signal });
    const body = await res.text();
    if (!res.ok || !body.includes("<urlset")) throw new Error(`Backend returned ${res.status}`);
    return new Response(body, {
      status: 200,
      headers: {
        "content-type": "application/xml; charset=utf-8",
        // Serve from the CDN for an hour, then keep serving the old copy for up to a
        // week while a fresh one is fetched in the background.
        "cache-control": "public, max-age=0, s-maxage=3600, stale-while-revalidate=604800",
      },
    });
  } catch (err) {
    console.error("sitemap: backend unavailable", err);
    return new Response("Sitemap temporarily unavailable", {
      status: 503,
      headers: { "content-type": "text/plain", "cache-control": "no-store", "retry-after": "120" },
    });
  } finally {
    clearTimeout(timer);
  }
}
